### ISSUE TITLE
Some tests fail when run from VS Test Explorer?

### ISSUE THREAD

**Issue by adamralph** [config-r/config-r#187]
(from https://github.com/urig/config-r/issues/1 raised by @urig)

Hi @adamralph. Maybe you can help me understand why some unit tests fail when I run them from the Visual Studio Test Explorer?

Before running the tests I had to install the "xUnit.net [Visual Studio Runner]" NuGet package for VS to even recognize the unit tests.

Below is an example of the first test that failed. Any idea why the test tries to access a forbidden path under 'C:\PROGRAM FILES (X86)'?

Thanks for your time and patience.

@urig

```
Test Name:  ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType
Test FullName:  ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType
Test Source:    d:\dev\config-r\src\test\ConfigR.Features\AnonymousTypesFeature.cs : line 24
Test Outcome:   Failed
Test Duration:  0:00:00.005

Result1 Name:   ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType() [01.01.02] Given a local config file containing an anonymous type with a Bar of 'baz'
Result1 Outcome:    Failed
Result1 Duration:   0:00:00.001
Result1 Message:    System.UnauthorizedAccessException : Access to the path 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe.csx' is denied.
Result1 StackTrace: 
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ConfigR.Features.AnonymousTypesFeature.<RetrievingAnAnonymousType>b__6() in d:\dev\config-r\src\test\ConfigR.Features\AnonymousTypesFeature.cs:line 30
   at Xbehave.Sdk.SyncStep.<>c__DisplayClass2.<Execute>b__0(Object o)

Result2 Name:   ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType() [01.01.03] When I get the anonymous type
Result2 Outcome:    Failed
Result2 Duration:   0:00:00.001
Result2 Message:    System.InvalidOperationException : Failed to execute preceding step "[01.01.02] Given a local config file containing an anonymous type with a Bar of 'baz'".
Result2 StackTrace: at Xbehave.Sdk.StepCommand.Execute(Object testClass)

Result3 Name:   ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType() [01.01.04] Then the anonymous type has a Bar of 'baz'
Result3 Outcome:    Failed
Result3 Duration:   0:00:00.001
Result3 Message:    System.InvalidOperationException : Failed to execute preceding step "[01.01.02] Given a local config file containing an anonymous type with a Bar of 'baz'".
Result3 StackTrace: at Xbehave.Sdk.StepCommand.Execute(Object testClass)

Result4 Name:   ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType() [01.01.01] (Background) Given no configuration has been loaded
Result4 Outcome:    Passed
Result4 Duration:   0:00:00.001
Result4 Message:
Result4 StackTrace:

Result5 Name:   ConfigR.Features.AnonymousTypesFeature.RetrievingAnAnonymousType() [01.01.05] (Teardown)
Result5 Outcome:    Passed
Result5 Duration:   0:00:00.001
Result5 Message:
Result5 StackTrace:
```

**Comment by adamralph** [comment]
@urig thanks for raising this. I've fixed it. Please pull down the latest dev branch and give it another try.
